### ISSUE TITLE
Breadcrumbs URL bug

### ISSUE THREAD

**Issue by adibi83** [Haaretz/htz-frontend#638] opened 2018-07-19 11:03 UTC
## Issue Type

**Bug fix**

## Description
Breadcrumbs click causes a fault in the URL, (the number is useless) e.g: 
https://www.haaretz.co.il/news/politi/2.696
https://www.haaretz.co.il/news/2.409

**Comment by kedarguy** [comment] 2018-07-24 01:15
The problem is the base domain is react-prod, once it will be in production it will work, after getting the 404 if you switch the react-prod to www it works

**Closed** 2018-08-12 11:28 UTC
Labels: bug
